added calender
kaladin9017/Game-Dash pull request #4
Opened 2017-01-31 18:50 UTC by bethea28

2017-01-31 19:28 UTC, kaladin9017 requested changes
Just add the calendar file, the clock file, and css file. It should be inside the style folder.

2017-02-02 15:51 UTC, nmadd commented on public/bundle.js
add your bundle file to .gitignore. you don't want them showing up in pull requests

2017-02-02 15:51 UTC, nmadd commented on src/components/widgets/calender/calender.js
> +
Clean this up! Formatting is a mess

2017-02-02 15:51 UTC, nmadd commented on src/components/widgets/calender/calender.js
> +
remove all console.logs before opening a pull request. console.logs shouldn't get merged into your main repo

2017-02-02 15:51 UTC, nmadd commented on src/components/widgets/calender/calender.js
> +  console.log(this.state)
remove console.log

2017-02-02 15:51 UTC, nmadd commented on src/components/widgets/calender/calender.js
> +   return(
fix formatting

2017-02-02 15:51 UTC, nmadd commented on src/components/widgets/calender/calender.js
> +          <Clock/>
fix formatting

2017-02-02 15:51 UTC, nmadd commented on src/components/widgets/calender/clock.js
> +  return(
fix formatting

2017-02-02 15:51 UTC, nmadd commented on src/components/widgets/calender/clock.js
> + componentDidMount(){
fix formatting

2017-02-02 15:51 UTC, nmadd commented on src/components/widgets/calender/clock.js
> +
fix formatting

2017-02-02 15:51 UTC, nmadd commented on src/components/widgets/calender/clock.js
> +   })
remove commented out code before opening a pull request. commented out code should not get merged into master

2017-02-02 15:51 UTC, nmadd commented on src/components/widgets/calender/clock.js
> +  console.log(this.state)
remove console.log

2017-02-02 15:51 UTC, nmadd commented on src/components/widgets/calender/clock.js
> +
fix formatting

2017-02-02 15:51 UTC, nmadd commented on src/components/widgets/calender/calender.js
> +
fix formatting

2017-02-02 15:51 UTC, nmadd commented on src/components/widgets/calender/calender.js
> +
fix formatting

2017-02-03 08:33 UTC, closed without merging